steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '--build-arg',
         'RELEASE_VERSION=${_NODE_RELEASE_VERSION}',
         '-t',
         'gcr.io/$PROJECT_ID/$REPO_NAME-node:${_NODE_RELEASE_VERSION}',
         '-f',
         'Dockerfile',
         '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME-node:${_NODE_RELEASE_VERSION}']
substitutions:
  _NODE_RELEASE_VERSION: 0.0.1
options:
  machineType: 'E2_HIGHCPU_32'